server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://laundry-em-db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL}
    properties:
      hibernate:
        format_sql: true
